# Generated by Django 3.0.8 on 2020-07-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotornot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hot_post',
            name='hottimage',
            field=models.ImageField(blank=True, upload_to='media/Hot_posts/%Y/%m/%d'),
        ),
    ]
