# Generated by Django 3.0.8 on 2020-07-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotornot', '0003_auto_20200724_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hot_post',
            name='hotimage',
            field=models.ImageField(upload_to='media/Hot_posts/%Y/%m/%d'),
        ),
    ]
