# Generated by Django 3.0.8 on 2020-07-29 06:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotornot', '0004_auto_20200728_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='hot_post',
            name='likes',
            field=models.ManyToManyField(related_name='liking_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
