# Generated by Django 3.0.8 on 2020-07-30 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotornot', '0006_auto_20200730_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hot_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotcaption', models.TextField()),
                ('hotimage', models.ImageField(upload_to='media/Hot_posts/%Y/%m/%d')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('likes', models.ManyToManyField(related_name='liking_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
