# Generated by Django 3.0.8 on 2020-07-30 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotornot', '0007_auto_20200730_1950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hot_post',
            old_name='user',
            new_name='author',
        ),
    ]
