# Generated by Django 3.0.8 on 2020-07-31 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotornot', '0009_auto_20200730_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hotornot.Post')),
                ('user', models.ManyToManyField(related_name='liking_User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
