# Generated by Django 3.0.6 on 2020-07-02 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0005_auto_20200702_1233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='postimage',
        ),
    ]
