# Generated by Django 3.0.6 on 2020-07-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0007_auto_20200702_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postimage',
            field=models.ImageField(blank=True, upload_to='media/%Y/%m/%d'),
        ),
    ]
