# Generated by Django 3.0.6 on 2020-07-03 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userpage', '0010_auto_20200703_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userpage.Post')),
                ('user', models.ManyToManyField(related_name='linkingUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
