# Generated by Django 3.0.6 on 2020-07-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0011_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
