# Generated by Django 3.0.6 on 2020-07-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0012_like_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userImage',
            field=models.ImageField(default='media/images/user.png', upload_to="media/profiles/%Y/%m/%d'"),
        ),
    ]
