# Generated by Django 3.0.6 on 2020-07-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0015_auto_20200707_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userImage',
            field=models.ImageField(blank=True, default='profiles/user.png', upload_to="media/profiles/%Y/%m/%d'"),
        ),
    ]
