# Generated by Django 3.0.6 on 2020-07-13 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0016_auto_20200707_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='likes',
        ),
    ]
