# Generated by Django 3.0.6 on 2020-07-13 13:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userpage', '0017_remove_like_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ManyToManyField(related_name='likingUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
