# Generated by Django 3.0.7 on 2020-07-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0018_auto_20200713_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userImage',
            field=models.ImageField(default='media/user.png', upload_to="media/profiles/%Y/%m/%d'"),
        ),
    ]
