# Generated by Django 3.0.7 on 2020-07-14 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0019_auto_20200714_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userImage',
            field=models.ImageField(default='user.png', upload_to="media/profiles/%Y/%m/%d'"),
        ),
    ]
