# Generated by Django 3.0.8 on 2020-08-11 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0022_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='Post_Comment',
        ),
    ]
