# Generated by Django 3.0.8 on 2020-08-13 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0024_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
