# Generated by Django 3.0.8 on 2020-08-13 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0025_remove_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_replies', to='userpage.Comment'),
        ),
    ]
