# Generated by Django 3.0.8 on 2020-08-13 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0027_auto_20200813_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_reply',
        ),
    ]
